import { useState, type ReactNode } from 'react';
import { vtShared } from '../../lib/viewTransition';
import { DEFAULT_ACCENT, coverBackground } from './theme';
import { resolveEssayMedia } from './media';

/**
 * Shared essay cover surface. Archive covers resolve through the same generated
 * AVIF/WebP manifest as inline images; local editorial covers retain the
 * conventional 640/full sibling fallback generated by the media pipeline.
 */
interface EssayCoverProps {
  src: string;
  alt: string;
  accent?: string;
  kicker?: string;
  focusY?: string;
  overlayFrom?: string;
  ornamentClass?: string;
  imgClassName?: string;
  loading?: 'eager' | 'lazy';
  className?: string;
  sharedName?: string;
  children?: ReactNode;
}

export default function EssayCover({
  src,
  alt,
  accent = DEFAULT_ACCENT,
  kicker,
  focusY = '20%',
  overlayFrom = '#050505',
  ornamentClass = 'text-[9rem]',
  imgClassName = '',
  loading = 'lazy',
  className = '',
  sharedName,
  children,
}: EssayCoverProps) {
  const [imgOk, setImgOk] = useState(true);
  const [loaded, setLoaded] = useState(false);
  const media = resolveEssayMedia({ src });

  return (
    <div
      className={`relative overflow-hidden ${className}`}
      style={{
        background: coverBackground(accent, focusY),
        ...(media.placeholder
          ? {
              backgroundImage: `url(${media.placeholder}), ${coverBackground(accent, focusY)}`,
              backgroundPosition: 'center',
              backgroundSize: 'cover',
            }
          : undefined),
        ...(sharedName ? vtShared(sharedName) : undefined),
      }}
    >
      {imgOk ? (
        <picture className="block h-full w-full leading-none">
          {media.avifSrcSet && <source type="image/avif" srcSet={media.avifSrcSet} sizes="(max-width: 768px) 94vw, 960px" />}
          {media.webpSrcSet && <source type="image/webp" srcSet={media.webpSrcSet} sizes="(max-width: 768px) 94vw, 960px" />}
          <img
            src={media.fallback}
            alt={alt}
            width={media.width}
            height={media.height}
            className={`essay-cover-image block h-full w-full object-cover ${loaded ? 'is-loaded' : ''} ${imgClassName}`}
            onLoad={() => setLoaded(true)}
            onError={() => {
              setLoaded(true);
              setImgOk(false);
            }}
            loading={loading}
            decoding="async"
            fetchPriority={loading === 'eager' ? 'high' : 'auto'}
            data-testid="essay-cover-image"
            data-loaded={loaded ? 'true' : 'false'}
          />
        </picture>
      ) : (
        <div className="flex h-full w-full items-center justify-center" data-testid="essay-cover-fallback">
          <span className={`font-serif ${ornamentClass} leading-none opacity-10`} style={{ color: accent }}>
            «»
          </span>
        </div>
      )}

      <div
        className="pointer-events-none absolute inset-0"
        style={{ background: `linear-gradient(to top, ${overlayFrom} 0%, ${overlayFrom}33 22%, transparent 55%)` }}
      />

      {kicker && (
        <span
          className="absolute left-5 top-5 rounded-full border px-4 py-1.5 text-[10px] font-bold uppercase tracking-[0.24em] backdrop-blur-md"
          style={{ color: accent, borderColor: `${accent}55`, backgroundColor: `${accent}18` }}
        >
          {kicker}
        </span>
      )}

      {children}
    </div>
  );
}
