import fs from 'node:fs';
import path from 'node:path';
import { sectionAnchor } from '../src/components/essay/anchor';
import { essays } from '../src/data/essays/index';
import { titleCase } from '../src/utils/titleCase';

const target = path.resolve('src/data/essaySearchIndex.generated.ts');

const entries = essays.map(({ id, title, excerpt, slug, blocks }) => {
  const sections = blocks.flatMap((block) => (
    block.type === 'section'
      ? [{
          heading: titleCase(block.heading),
          anchor: sectionAnchor(block.heading, block.anchor),
        }]
      : []
  ));

  const anchors = sections.map((section) => section.anchor);
  if (new Set(anchors).size !== anchors.length) {
    throw new Error(`Duplicate essay section anchor in ${slug}`);
  }

  return { id, title, excerpt, slug, sections };
});

const sectionCount = entries.reduce((count, entry) => count + entry.sections.length, 0);
const source = `/* Generated by scripts/gen-essay-search-index.ts. Do not edit manually. */\n\nexport interface EssaySearchSection {\n  heading: string;\n  anchor: string;\n}\n\nexport interface EssaySearchEntry {\n  id: string;\n  title: string;\n  excerpt: string;\n  slug: string;\n  sections: readonly EssaySearchSection[];\n}\n\nexport const essaySearchIndex: readonly EssaySearchEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

fs.writeFileSync(target, source, 'utf8');
console.log(`essay search index: ${entries.length} published entries, ${sectionCount} canonical sections`);
