import fs from 'node:fs';
import path from 'node:path';
import { essays } from '../src/data/essays/index';

const target = path.resolve('src/data/essaySearchIndex.generated.ts');
const entries = essays.map(({ id, title, excerpt, slug }) => ({ id, title, excerpt, slug }));
const source = `/* Generated by scripts/gen-essay-search-index.ts. Do not edit manually. */\n\nexport interface EssaySearchEntry {\n  id: string;\n  title: string;\n  excerpt: string;\n  slug: string;\n}\n\nexport const essaySearchIndex: readonly EssaySearchEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

fs.writeFileSync(target, source, 'utf8');
console.log(`essay search index: ${entries.length} published entries`);
