import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const read = (file: string) => fs.readFileSync(path.resolve(file), 'utf8');
const reveal = read('src/components/Reveal.tsx');
const home = read('src/pages/HomePage.tsx');
const heroWindowCss = read('src/components/home/hero-poet-window.css');
const safariSpec = read('qa/mobile-webkit-isolated.spec.mjs');
const helpers = read('qa/mobile-webkit-isolated.helpers.mjs');
const packageJson = read('package.json');

assert.match(reveal, /type CSSProperties/);
assert.match(reveal, /export function useReliableInView/);
assert.match(reveal, /new IntersectionObserver/);
assert.match(reveal, /element\.getBoundingClientRect\(\)/);
assert.match(reveal, /window\.visualViewport/);
assert.match(reveal, /intersectionWidth \* intersectionHeight/);
assert.match(reveal, /intersectionRatio >= boundedThreshold/);
assert.match(reveal, /GEOMETRY_FALLBACK_DELAY_MS = 96/);
assert.match(reveal, /const clearScheduledGeometryCheck = \(\) => \{/);
assert.match(reveal, /window\.cancelAnimationFrame\(frame\)/);
assert.match(reveal, /window\.clearTimeout\(geometryFallbackTimer\)/);
assert.match(reveal, /const flushGeometryCheck = \(\) => \{[\s\S]*clearScheduledGeometryCheck\(\);[\s\S]*checkGeometry\(\);[\s\S]*\}/);
assert.match(reveal, /window\.requestAnimationFrame\(flushGeometryCheck\)/);
assert.match(reveal, /window\.setTimeout\(flushGeometryCheck, GEOMETRY_FALLBACK_DELAY_MS\)/);
assert.match(reveal, /if \(!frame\)[\s\S]*if \(!geometryFallbackTimer\)/);
assert.match(reveal, /new ResizeObserver\(scheduleGeometryCheck\)/);
assert.match(reveal, /window\.addEventListener\('scroll', scheduleGeometryCheck/);
assert.match(reveal, /document\.addEventListener\('scroll', scheduleGeometryCheck, \{ capture: true, passive: true \}\)/);
assert.match(reveal, /window\.addEventListener\('pageshow', scheduleGeometryCheck\)/);
assert.match(reveal, /document\.addEventListener\('visibilitychange', scheduleGeometryCheck\)/);
assert.match(reveal, /window\.visualViewport\?\.addEventListener\('scroll', scheduleGeometryCheck/);
assert.match(reveal, /window\.visualViewport\?\.addEventListener\('resize', scheduleGeometryCheck/);
assert.match(reveal, /BOOTSTRAP_CHECK_DELAYS_MS = \[0, 80, 240, 600, 1_200, 2_200\]/);
assert.match(reveal, /window\.setTimeout\(scheduleGeometryCheck, delay\)/);
assert.match(reveal, /clearScheduledGeometryCheck\(\);[\s\S]*for \(const timer of delayedChecks\) window\.clearTimeout\(timer\)/);
assert.match(reveal, /document\.removeEventListener\('scroll', scheduleGeometryCheck, true\)/);
assert.match(reveal, /observer\.disconnect\(\)/);
assert.match(reveal, /resizeObserver\?\.disconnect\(\)/);

assert.match(reveal, /REVEAL_EASING = 'cubic-bezier\(0\.16, 1, 0\.3, 1\)'/);
assert.match(reveal, /const style: CSSProperties = \{/);
assert.match(reveal, /opacity: revealed \? 1 : 0/);
assert.match(reveal, /transform: revealed \? 'translate3d\(0, 0, 0\)' : hiddenTransform\(direction, distance\)/);
assert.match(reveal, /filter: !revealed && blur && !prefersReduced \? 'blur\(6px\)' : 'blur\(0px\)'/);
assert.match(reveal, /transition,/);
assert.match(reveal, /willChange: revealed \? 'auto' : 'opacity, transform, filter'/);
assert.match(reveal, /data-reveal-state=\{revealed \? 'visible' : 'hidden'\}/);
assert.match(reveal, /<div[\s\S]*ref=\{ref\}[\s\S]*style=\{style\}/);
assert.doesNotMatch(reveal, /<motion\.div|initial=|animate=|variants=|makeVariants/);
assert.doesNotMatch(reveal, /setInterval|classList\.(?:add|remove)|style\.opacity\s*=|setAttribute\(['"]style/);

assert.match(home, /import Reveal, \{ useReliableInView \} from '\.\.\/components\/Reveal'/);
assert.doesNotMatch(home, /\buseInView\b/);
assert.match(home, /useReliableInView<HTMLDivElement>\(\{ once: true, threshold: 0\.1 \}\)/);
assert.match(home, /<Reveal[\s\S]*key=\{stat\.label\}[\s\S]*distance=\{20\}[\s\S]*blur=\{false\}/);
assert.doesNotMatch(home, /whileInView=/);

const touchFirstViewportPolicy = /@media \(hover: none\) and \(pointer: coarse\), \(max-width: 1024px\) \{[\s\S]*?\.w-full:has\(> \.hero-title-lockup\),[\s\S]*?\[data-hero-poet-window-shell\],[\s\S]*?\.hero-blur-reveal,[\s\S]*?\.hero-blur-reveal-strong \{([\s\S]*?)\n  \}/;
const touchFirstViewportMatch = heroWindowCss.match(touchFirstViewportPolicy);
assert.ok(touchFirstViewportMatch, 'touch/compact first viewport must have one shared static readability policy');
const touchFirstViewportDeclarations = touchFirstViewportMatch[1];
assert.match(touchFirstViewportDeclarations, /animation: none !important/);
assert.match(touchFirstViewportDeclarations, /transition: none !important/);
assert.match(touchFirstViewportDeclarations, /opacity: 1 !important/);
assert.match(touchFirstViewportDeclarations, /transform: none !important/);
assert.match(touchFirstViewportDeclarations, /will-change: auto !important/);
assert.match(heroWindowCss, /@media \(hover: hover\) and \(pointer: fine\)/);
assert.match(heroWindowCss, /animation-name: hero-premium-reveal-optimized !important/);
assert.doesNotMatch(touchFirstViewportDeclarations, /display: none|visibility: hidden|pointer-events: none/);

assert.match(safariSpec, /expect\(visual\.effectiveOpacity[\s\S]*toBeGreaterThan\(0\.9\)/);
assert.match(safariSpec, /expect\(visual\.blurPx[\s\S]*toBeLessThanOrEqual\(0\.05\)/);
assert.match(helpers, /node\.scrollIntoView\(\{ block: 'center', inline: 'nearest', behavior: 'instant' \}\)/);
assert.match(helpers, /WEBKIT_VIEWPORT_SETTLE_MS = 700/);
assert.match(helpers, /WEBKIT_MIN_STABLE_INTERSECTION = 0\.55/);
assert.match(helpers, /intersectionRatio: \(intersectionWidth \/ visibleWidthBase\) \* \(intersectionHeight \/ visibleHeightBase\)/);
assert.match(helpers, /await centerLocatorNatively\(target\);[\s\S]*await page\.waitForTimeout\(WEBKIT_VIEWPORT_SETTLE_MS\);[\s\S]*await centerLocatorNatively\(target\)/);
assert.match(helpers, /first\.intersectionRatio < WEBKIT_MIN_STABLE_INTERSECTION/);
assert.match(helpers, /second\.intersectionRatio >= WEBKIT_MIN_STABLE_INTERSECTION/);
assert.match(helpers, /Math\.abs\(second\.centerDelta\) <= Math\.max\(64, second\.viewportHeight \* 0\.4\)/);
assert.match(helpers, /substantially visible in the WebKit visual viewport after native two-phase centering/);
assert.doesNotMatch(helpers, /scrollIntoViewIfNeeded|page\.mouse\.wheel|classList\.(?:add|remove)|style\.opacity\s*=/);
assert.match(packageJson, /"validate:reliable-reveal": "tsx scripts\/validate-reliable-reveal\.ts"/);
assert.match(packageJson, /brand:materialize && npm run validate:reliable-reveal && npm run validate:brand-browser-workflow/);
assert.doesNotMatch(packageJson, /validate:brand-v20/);

console.log('reliable reveal validation: below-fold geometry races requestAnimationFrame against one bounded timeout fallback, touch/compact first viewport remains readable without animation clocks, and desktop fine-pointer choreography plus strict Safari opacity/blur verdicts stay intact');
