import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
const read=(file:string)=>fs.readFileSync(path.resolve(file),'utf8');
const bytes=(file:string)=>fs.readFileSync(path.resolve(file));
const sha256=(file:string)=>crypto.createHash('sha256').update(bytes(file)).digest('hex');
const gitBlobSha=(file:string)=>{const body=bytes(file);return crypto.createHash('sha1').update(`blob ${body.length}\0`).update(body).digest('hex')};
function crc32(buffer:Buffer){let crc=0xffffffff;for(const byte of buffer){crc^=byte;for(let bit=0;bit<8;bit+=1)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return(crc^0xffffffff)>>>0}
function pngSize(file:string){const buffer=bytes(file);assert.equal(buffer.subarray(0,8).toString('hex'),'89504e470d0a1a0a');let offset=8,dimensions:{width:number;height:number}|null=null;while(offset+12<=buffer.length){const length=buffer.readUInt32BE(offset),type=buffer.subarray(offset+4,offset+8).toString('ascii'),end=offset+8+length;assert.ok(end+4<=buffer.length);assert.equal(crc32(buffer.subarray(offset+4,end)),buffer.readUInt32BE(end));if(type==='IHDR')dimensions={width:buffer.readUInt32BE(offset+8),height:buffer.readUInt32BE(offset+12)};offset=end+4;if(type==='IEND')break}assert.ok(dimensions);return dimensions}
function jpegSize(file:string){const buffer=bytes(file);assert.equal(buffer[0],0xff);assert.equal(buffer[1],0xd8);const sof=new Set([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf]);let offset=2;while(offset+9<buffer.length){if(buffer[offset]!==0xff){offset+=1;continue}while(buffer[offset]===0xff)offset+=1;const marker=buffer[offset];if(marker===0xda||marker===undefined)break;if(marker===0xd8||marker===0xd9||marker===0x01||(marker>=0xd0&&marker<=0xd7)){offset+=1;continue}const length=buffer.readUInt16BE(offset+1);if(sof.has(marker))return{height:buffer.readUInt16BE(offset+4),width:buffer.readUInt16BE(offset+6)};offset+=1+length}throw new Error(`${file}: JPEG dimensions not found`)}
function assertCompleteSvg(source:string,file:string,viewBox:string){const escaped=viewBox.split(' ').join('\\s+');assert.match(source,new RegExp(`<svg\\b[^>]*viewBox="${escaped}"`),`${file}: viewBox changed`);assert.ok(source.trimEnd().endsWith('</svg>'));assert.equal((source.match(/<svg\b/g)||[]).length,(source.match(/<\/svg>/g)||[]).length);assert.equal((source.match(/<defs\b/g)||[]).length,(source.match(/<\/defs>/g)||[]).length);const groups=(source.match(/<g(?:\s[^>]*)?>/g)||[]).filter(tag=>!/\/\s*>$/.test(tag));assert.equal(groups.length,(source.match(/<\/g>/g)||[]).length,`${file}: unbalanced groups`);assert.doesNotMatch(source,/<[^>]+\sdata-brand-[\w-]+(?=\s|>)(?!\s*=)/)}
const component=read('src/components/BrandMark.tsx'),standalone=read('public/brand-emblem.svg'),micro=read('public/brand-mark-micro.svg'),mask=read('public/brand-emblem-mask.svg'),index=read('index.html'),browserconfig=read('public/browserconfig.xml'),materializer=read('scripts/materialize-brand-art.mjs'),release=read('public/brand-release.txt');
const manifest=JSON.parse(read('public/site.webmanifest')) as {icons?:Array<{src?:string}>};
const evaluation=JSON.parse(read('qa/brand-reference-evaluation.json')) as {candidateSource:string;candidateRevision:string;reviewerDecision:string;candidateGitBlobShas:Record<string,string>};
const version='cloak-20260729-17',vectorSource='canonical-reference-v2-crushed-depth-parallax-v15-0',masterSha256='f9e29065cc7191827750d252ecb8b8002385671faed5a4503dd2738065f661b7';
const hooks=['mark','vector','figure','hood','cloak','face-void','face-depth','rim-light','folds','collar','atmosphere','energy','texture','seams','hood-layers','neck-shadow'];
for(const token of ['useId()','useReducedMotion()','requestAnimationFrame(','cancelAnimationFrame(','data-brand-interaction="idle"','data-brand-parallax="layered-v1"','@media (hover:hover) and (pointer:fine)','@media (prefers-reduced-motion:reduce)','pointerType!==\'touch\'','pointerEvents:\'none\''])assert.ok(component.includes(token),`component missing ${token}`);
for(const variable of ['--brand-atmosphere-x','--brand-energy-x','--brand-figure-x','--brand-folds-x','--brand-hood-x','--brand-hood-layers-x','--brand-face-x','--brand-collar-x','--brand-rim-x','--brand-texture-x'])assert.ok(component.includes(variable),`${variable}: missing depth channel`);
for(const hook of hooks)assert.ok(component.includes(`data-brand-${hook}`),`data-brand-${hook} missing`);
assert.ok(component.includes(`const VECTOR_SOURCE = '${vectorSource}'`));assert.ok(component.includes(`const BRAND_VERSION = '${version}'`));assert.ok(component.includes('data-brand-vector-source={VECTOR_SOURCE}'));assert.ok(component.includes('M48 32.1C41.4 31.9'));assert.ok(component.includes('M47.8 9.4C43.5 10.1'));assert.ok(component.includes('M46.9 17.2C44.3 17.7'));assert.ok((component.match(/<path\b/g)||[]).length>=28);assert.ok((component.match(/(?:^|[\s"'])M/g)||[]).length>=32);assert.doesNotMatch(component,/<(?:motion\.)?image\b|<img\b|data:image|base64,|<rect\b|transition-all/i);
assertCompleteSvg(standalone,'public/brand-emblem.svg','0 0 96 96');assert.ok(standalone.includes(`data-brand-vector-source="${vectorSource}"`));for(const token of ['M48 32.1C41.4 31.9','M47.8 9.4C43.5 10.1','M46.9 17.2C44.3 17.7','@media (hover:hover) and (pointer:fine)','@media (prefers-reduced-motion:reduce)'])assert.ok(standalone.includes(token));assert.ok((standalone.match(/<path\b/g)||[]).length>=35);assert.doesNotMatch(standalone,/<(?:image|rect)\b|data:image|base64,/i);
const atmosphereStart=standalone.indexOf('<g data-brand-atmosphere='),atmosphereEnd=standalone.indexOf('<g data-brand-energy=',atmosphereStart);assert.ok(atmosphereStart>=0&&atmosphereEnd>atmosphereStart);for(const match of standalone.slice(atmosphereStart,atmosphereEnd).matchAll(/d="([^"]+)"/g)){const numbers=(match[1].match(/-?\d+(?:\.\d+)?/g)||[]).map(Number),ys=numbers.filter((_,index)=>index%2===1);assert.ok(ys.every(value=>value<=68),'upper-side atmosphere became lower-edge smoke')}
assertCompleteSvg(micro,'public/brand-mark-micro.svg','0 0 32 32');assert.ok(micro.includes(`data-brand-vector-source="${vectorSource}"`));for(const token of ['M16 10.7C13.9 10.6','M15.9 2.7C14.6 3','M15.7 4.7C14.9 4.9'])assert.ok(micro.includes(token));assert.ok((micro.match(/<path\b/g)||[]).length>=20);assert.doesNotMatch(micro,/<(?:image|rect)\b|data:image|base64,/i);
assertCompleteSvg(mask,'public/brand-emblem-mask.svg','0 0 96 96');assert.ok(mask.includes('fill-rule="evenodd"'));assert.ok(mask.includes('M47.8 9.4C43.5 10.1'));assert.ok(mask.includes('M46.9 17.2C44.3 17.7'));assert.doesNotMatch(mask,/<(?:image|rect)\b|data:image|base64,/i);
assert.equal(evaluation.candidateSource,vectorSource);assert.match(evaluation.candidateRevision,/v15\.0/);assert.equal(evaluation.reviewerDecision,'not-reference-approved');for(const file of ['src/components/BrandMark.tsx','public/brand-emblem.svg','public/brand-mark-micro.svg','public/brand-emblem-mask.svg'])assert.equal(gitBlobSha(file),evaluation.candidateGitBlobShas[file],`${file}: Git blob differs from reference lock`);
for(const pattern of [`name="brand-release" content="${version}"`,`brand-mark-micro\\.svg\\?v=${version}`,`favicon-32\\.png\\?v=${version}`,`favicon-16\\.png\\?v=${version}`,`apple-touch-icon\\.png\\?v=${version}`,`brand-emblem-mask\\.svg\\?v=${version}`,`site\\.webmanifest\\?v=${version}`,`og-image\\.jpg\\?v=${version}`,`icon-512\\.png\\?v=${version}`])assert.match(index,new RegExp(pattern));
assert.equal(release.trim(),`${version}\nmaster-sha256=${masterSha256}`);const sources=new Set((manifest.icons||[]).map(icon=>icon.src));for(const src of [`/favicon-32.png?v=${version}`,`/icon-192.png?v=${version}`,`/icon-512.png?v=${version}`,`/icon-maskable-512.png?v=${version}`])assert.ok(sources.has(src));assert.match(browserconfig,new RegExp(`mstile-150x150\\.png\\?v=${version}`));
for(const embedded of ['master-320-q92.webp.b64','favicon-16.png.b64','favicon-32.png.b64']){assert.ok(materializer.includes(embedded));assert.ok(fs.existsSync(path.resolve('src/brand-assets',embedded)))}
const hashes:Record<string,string>={'public/brand-emblem-master.webp':masterSha256,'public/favicon-16.png':'b613d63da2b88f9c798ec171173fa86aa6d48aea5e59da7d64cce18ff4a8cd9c','public/favicon-32.png':'27880a89ca75ef4ba8d8e21243cd189846e3213cd487fc921761965ec2d55622'};for(const[file,expected]of Object.entries(hashes))assert.equal(sha256(file),expected);
const pngs:Record<string,{width:number;height:number}>={'public/favicon-16.png':{width:16,height:16},'public/favicon-32.png':{width:32,height:32},'public/apple-touch-icon.png':{width:180,height:180},'public/icon-192.png':{width:192,height:192},'public/icon-512.png':{width:512,height:512},'public/icon-maskable-512.png':{width:512,height:512},'public/mstile-150x150.png':{width:150,height:150}};for(const[file,expected]of Object.entries(pngs))assert.deepEqual(pngSize(file),expected);assert.deepEqual(jpegSize('public/og-image.jpg'),{width:1200,height:630});console.log('brand validation: v15.0 synchronized vector geometry, eleven-layer pointer depth, reduced-motion fallback and smoke-free lower edge are consistent');
