/* Generated by scripts/gen-essay-search-index.ts. Do not edit manually. */

export interface EssaySearchEntry {
  id: string;
  title: string;
  excerpt: string;
  slug: string;
}

export const essaySearchIndex: readonly EssaySearchEntry[] = [];
