import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const BASE_URL=process.env.QA_BASE_URL||'http://127.0.0.1:4173',DIR=path.resolve('qa-artifacts'),VERSION='cloak-20260729-20',SOURCE='canonical-reference-v2-black-monolith-v17-0';
const reference=`data:image/webp;base64,${fs.readFileSync(path.resolve('qa/reference/brand-emblem-canonical-reference.webp')).toString('base64')}`;fs.mkdirSync(DIR,{recursive:true});
const css=`*{box-sizing:border-box}html,body{margin:0;background:#03070d;color:#d9f8ff;font:14px system-ui}main{padding:28px}h1{margin:0 0 8px}.sub{color:#8ebcca;margin-bottom:22px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.col{display:grid;justify-items:center;gap:8px}.tile{width:204px;height:204px;display:grid;place-items:center;background:#010306;border:1px solid #18313a;overflow:hidden}.decision{color:#ffb27a;font-weight:700}.top{display:grid;grid-template-columns:1fr 1fr;gap:18px}.panel{height:340px;display:grid;place-items:center;background:#010306;border:1px solid #18313a;overflow:hidden}.panel img{max-width:100%;max-height:100%;object-fit:contain}.live{margin-top:18px}.live .panel{height:320px;background:#050810}.live img{width:100%;height:100%;object-fit:contain}`;

test('reference v2 is rendered above every v17 optical size',async({page})=>{await page.setViewportSize({width:1240,height:900});const sizes=[192,96,56,32,16],cols=sizes.map(n=>`<section class=col><b>${n}px</b><div class=tile><img data-kind=ref width=${n} height=${n} src="${reference}"></div><small>REFERENCE V2</small><div class=tile><img data-kind=candidate width=${n} height=${n} src="${BASE_URL}/${n<=32?'brand-mark-micro.svg':'brand-emblem.svg'}?v=${VERSION}"></div><small>CURRENT v17.0</small></section>`).join('');await page.setContent(`<style>${css}</style><main><h1>CANONICAL REFERENCE V2 / CURRENT v17.0</h1><div class=sub>Judge the high hood, compact irregular cavern, hidden throat, almost-black monolithic cloak, three broad fold families, curved upper-side energy and clean lower edge. <span class=decision>NOT REFERENCE APPROVED</span></div><div class=grid>${cols}</div></main>`);const ok=await page.locator('img').evaluateAll(async ns=>Promise.all(ns.map(async n=>{try{await n.decode();return n.naturalWidth>0}catch{return false}})));expect(ok.every(Boolean)).toBe(true);await page.screenshot({path:path.join(DIR,'brand-reference-comparison-matrix.png'),fullPage:true})});

test('reference v2 is compared with v17 SVG and exact checked homepage',async({page})=>{await page.setViewportSize({width:1440,height:1000});expect((await page.goto(BASE_URL,{waitUntil:'domcontentloaded'}))?.status()).toBeLessThan(400);await page.addStyleTag({content:'[data-custom-cursor-dot],[data-custom-cursor-ring]{display:none!important}'});const mark=page.locator('header [data-brand-mark]').first();await expect(mark).toHaveAttribute('data-brand-vector-source',SOURCE);await expect(mark).toHaveAttribute('data-brand-parallax','layered-v1');await page.screenshot({path:path.join(DIR,'brand-live-site-home-first-viewport.png'),fullPage:false});const h=await page.locator('header').first().boundingBox(),live=await page.screenshot({clip:{x:Math.max(0,h.x),y:Math.max(0,h.y),width:Math.min(1440,h.width),height:Math.min(340,h.height+80)}}),liveUrl=`data:image/png;base64,${live.toString('base64')}`;await page.setViewportSize({width:1320,height:900});await page.setContent(`<style>${css}</style><main><h1>REFERENCE V2 / v17.0 SVG / EXACT CHECKED BUILD</h1><div class="sub decision">NOT REFERENCE APPROVED</div><div class=top><div class=panel><img src="${reference}" width=300 height=300></div><div class=panel><img src="${BASE_URL}/brand-emblem.svg?v=${VERSION}" width=300 height=300></div></div><div class=live><div class=panel><img src="${liveUrl}"></div></div></main>`);const ok=await page.locator('img').evaluateAll(async ns=>Promise.all(ns.map(async n=>{try{await n.decode();return true}catch{return false}})));expect(ok.every(Boolean)).toBe(true);await page.screenshot({path:path.join(DIR,'brand-reference-live-site-comparison.png'),fullPage:true})});
